### ISSUE TITLE
Vendor Info

### ISSUE THREAD

**Issue by Smcner** [blue-button/bluebutton.js#145]
Is there any way to include EHR vendor information in the next pull?

**Comment by sankarravi** [comment]
It is possible to include vendor info in CDAs, but the section doesn't seem very widely used, and in the samples I've looked at, even when it's present, it's often not very useful.

The vendor lives in a `<assignedAuthoringDevice>` section, under a `manufacturerModelName` and `softwareName`. For your Epic sample, both of those say "Epic - Version 8.1"; for the Allscripts sample, they say "11.410.648.0" and "11.410.648.0; Transform 4.1.2.2."

If your goal is to handle differential behavior for different vendors, I've found it's better to approach this like browser-capability checks, rather than user-agent checking (e.g., checking whether a browser supports some HTML feature, rather than checking if the browser is named "Internet Explorer.") So instead of writing "if vendor is X, massage the data this way," I've found it's a lot easier to manage / more versatile to write, "if the data looks like X, massage it this way" (a few real ones we've run into: "if the med name has '(free text)' in it, throw that out" [Allscripts]; "if the med sig is the same as the med name, leave the med sig blank" [eCW]; "if there's a structured and unstructured sig but the former contains only a route, use the latter" [Greenway].

But if you do find that you really want the vendor name and are ok with it being often empty, you can edit the two parsers/*/documents.js files to extract the fields I mentioned above.

**Comment by Smcner** [comment]
I definitely see what you're saying - the main reason I want the vendor info is simply to display for presentation purposes. I work for a public health agency in the city and I am try to show the benefits of handling CDA, whether as a HISP, patient engagement, or simply assisting providers switching vendors. There's some skepticism that it's not possible to accurately translate CDA from different vendors but with the changes made in the last few weeks I'm hitting about 90% of the clinically relevant data. I'm building a web-based app and it'd be cool to show the vendor info pulled directly from the code just to prove a point.

**Comment by sankarravi** [comment]
Makes sense. The code should look like:

```
el = doc.tag('assignedAuthoringDevice')
var software_vendor_name = el.tag('manufacturerModelName').val();
var software_name = el.tag('softwareName').val();
```

and then add software_vendor_name and software_name to the `data` dict at the bottom so it makes it into your JSON. This is in document.js (probably both the CCDA and C32 versions, assuming you'll be running into both version)

[Didn't test that so might be a typo in there but that should be pretty close]
